name: photography_guide
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  timelines_plus: ^1.0.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
    # Beginner Assets
    - assets/Beginner_Asset/day 1 comp/
    - assets/Beginner_Asset/day 2 comp/
    - assets/Beginner_Asset/day 3 comp/
    - assets/Beginner_Asset/day 4 comp/
    - assets/Beginner_Asset/day 5 comp/
    - assets/Beginner_Asset/day 6 comp/
    - assets/Beginner_Asset/day 7 comp/
    - assets/Beginner_Asset/day 8 comp/
    - assets/Beginner_Asset/day 9 comp/
    - assets/Beginner_Asset/day 10 comp/
    - assets/Beginner_Asset/day 11 comp/
    - assets/Beginner_Asset/day 12 comp/
    - assets/Beginner_Asset/day 13 comp/
    - assets/Beginner_Asset/day 14 comp/
    - assets/Beginner_Asset/day 15 comp/
    - assets/Beginner_Asset/day 16 comp/
    - assets/Beginner_Asset/day 17 comp/
    - assets/Beginner_Asset/day 18 comp/
    - assets/Beginner_Asset/day 19 comp/
    - assets/Beginner_Asset/day 20 comp/
    - assets/Beginner_Asset/day 21 comp/
    - assets/Beginner_Asset/day 22 comp/
    - assets/Beginner_Asset/day 23 comp/
    - assets/Beginner_Asset/day 24/
    - assets/Beginner_Asset/day 25 comp/
    - assets/Beginner_Asset/day 26 comp/
    - assets/Beginner_Asset/day 27 comp/
    - assets/Beginner_Asset/day 28 comp/
    - assets/Beginner_Asset/day 29 comp/
    - assets/Beginner_Asset/day 30 comp/
    # Intermediate Assets
    - assets/Intermediate_Asset/Day 1 comp/
    - assets/Intermediate_Asset/Day 2 comp/
    - assets/Intermediate_Asset/Day 3 comp/
    - assets/Intermediate_Asset/Day 4 comp/
    - assets/Intermediate_Asset/Day 5 comp/
    - assets/Intermediate_Asset/Day 6 comp/
    - assets/Intermediate_Asset/Day 7 comp/
    - assets/Intermediate_Asset/Day 8 comp/
    - assets/Intermediate_Asset/Day 9 comp/
    - assets/Intermediate_Asset/Day 10 comp/
    - assets/Intermediate_Asset/Day 11 comp/
    - assets/Intermediate_Asset/Day 12 comp/
    - assets/Intermediate_Asset/day 13 comp/
    - assets/Intermediate_Asset/Day 14 comp/
    - assets/Intermediate_Asset/Day 15 comp/
    - assets/Intermediate_Asset/Day 16 comp/
    - assets/Intermediate_Asset/Day 17 comp/
    - assets/Intermediate_Asset/Day 18 comp/
    - assets/Intermediate_Asset/Day 19 comp/
    - assets/Intermediate_Asset/Day 20 comp/
    - assets/Intermediate_Asset/Day 21 comp/
    - assets/Intermediate_Asset/Day 22 comp/
    - assets/Intermediate_Asset/Day 23 comp/
    - assets/Intermediate_Asset/Day 24 comp/
    - assets/Intermediate_Asset/Day 25 comp/
    - assets/Intermediate_Asset/Day 26 comp/
    - assets/Intermediate_Asset/Day 27 comp/
    - assets/Intermediate_Asset/Day 28 comp /
    - assets/Intermediate_Asset/Day 29 comp/
    - assets/Intermediate_Asset/Day 30 comp/
    # Advanced Assets
    - assets/Advanced_Asset/Day 1 comp/
    - assets/Advanced_Asset/Day 2 comp/
    - assets/Advanced_Asset/Day 3 comp/
    - assets/Advanced_Asset/Day 4 comp/
    - assets/Advanced_Asset/Day 5 comp/
    - assets/Advanced_Asset/Day 6 comp/
    - assets/Advanced_Asset/Day 7 comp /
    - assets/Advanced_Asset/Day 8 comp/
    - assets/Advanced_Asset/Day 9 comp/
    - assets/Advanced_Asset/Day 10 comp/
    - assets/Advanced_Asset/Day 11 comp/
    - assets/Advanced_Asset/Day 12 comp/
    - assets/Advanced_Asset/Day 13 comp/
    - assets/Advanced_Asset/Day 14 comp/
    - assets/Advanced_Asset/Day 15 comp/
    - assets/Advanced_Asset/Day 16 comp/
    - assets/Advanced_Asset/Day 17 comp/
    - assets/Advanced_Asset/Day 18 comp/
    - assets/Advanced_Asset/Day 19 comp/
    - assets/Advanced_Asset/Day 20 comp/
    - assets/Advanced_Asset/Day 21 comp/
    - assets/Advanced_Asset/Day 22 comp/
    - assets/Advanced_Asset/Day 23 comp/
    - assets/Advanced_Asset/Day 24 comp/
    - assets/Advanced_Asset/Day 25 comp/
    - assets/Advanced_Asset/Day 26 comp/
    - assets/Advanced_Asset/Day 27 comp/
    - assets/Advanced_Asset/Day 28 comp/
    - assets/Advanced_Asset/Day 29 comp/
    - assets/Advanced_Asset/Day 30 comp/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
